const config = {
  STREAM_PLAYBACK_URL: process.env.REACT_APP_STREAM_PLAYBACK_URL,
  WEBSOCKET_URL: process.env.REACT_APP_WEBSOCKET_URL,
  CHANNEL_NAME: process.env.REACT_APP_CHANNEL_NAME,
  INTERVAL_SECONDS: process.env.REACT_APP_INTERVAL_SECONDS,
};

export default config;
